[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77.0.3"]

[project]
authors = [
  {name = "eagle"},
  {email = "eagle@42.fr"},
]
description = "A sample test package"
license = "MIT"
license-files = ["LICENSE"]
name = "ft_package"
readme = "README.md"
version = "0.0.1"

[project.urls]
"Home-page" = "https://github.com/eagle/ft_package"
